const emojiArray = [
  { character: '😊', shortName: 'smile', wrongNames: ['happy', 'joy', 'laugh'] },
  { character: '🌍', shortName: 'earth', wrongNames: ['world', 'globe', 'planet'] },
  { character: '🐱', shortName: 'cat', wrongNames: ['kitty', 'feline', 'meow'] },
  { character: '🍎', shortName: 'apple', wrongNames: ['fruit', 'red', 'juicy'] },
  { character: '🚗', shortName: 'car', wrongNames: ['vehicle', 'automobile', 'drive'] },
  { character: '🌈', shortName: 'rainbow', wrongNames: ['color', 'sky', 'weather'] },
  { character: '🎉', shortName: 'celebrate', wrongNames: ['party', 'fun', 'happy'] },
  { character: '📷', shortName: 'camera', wrongNames: ['photo', 'picture', 'snapshot'] },
  { character: '⌚', shortName: 'watch', wrongNames: ['timepiece', 'wristwatch', 'clock'] },
  { character: '🎮', shortName: 'gaming', wrongNames: ['game', 'play', 'console'] },
  { character: '🍕', shortName: 'pizza', wrongNames: ['slice', 'cheese', 'italian'] },
  { character: '🎸', shortName: 'guitar', wrongNames: ['music', 'instrument', 'strings'] },
  { character: '📚', shortName: 'book', wrongNames: ['reading', 'literature', 'novel'] },
  { character: '🌸', shortName: 'flower', wrongNames: ['blossom', 'petal', 'garden'] },
  { character: '🍦', shortName: 'icecream', wrongNames: ['dessert', 'sundae', 'cone'] },
  { character: '🎨', shortName: 'art', wrongNames: ['painting', 'creativity', 'canvas'] },
  { character: '🚀', shortName: 'rocket', wrongNames: ['space', 'launch', 'spacecraft'] },
  { character: '🎤', shortName: 'microphone', wrongNames: ['sing', 'voice', 'recording'] },
  { character: '🍔', shortName: 'burger', wrongNames: ['sandwich', 'fast food', 'beef'] },
  { character: '🏖️', shortName: 'beach', wrongNames: ['shore', 'coast', 'ocean'] },
  { character: '🚲', shortName: 'bike', wrongNames: ['bicycle', 'cycling', 'ride'] },
  { character: '🎈', shortName: 'balloon', wrongNames: ['inflate', 'party', 'float'] },
  { character: '☕', shortName: 'coffee', wrongNames: ['drink', 'caffeine', 'mug'] },
  { character: '🌮', shortName: 'taco', wrongNames: ['mexican', 'food', 'spicy'] },
  { character: '🎧', shortName: 'headphones', wrongNames: ['music', 'audio', 'earphones'] },
  { character: '🍓', shortName: 'strawberry', wrongNames: ['fruit', 'red', 'juicy'] },
  { character: '🏠', shortName: 'house', wrongNames: ['home', 'residence', 'building'] },
  { character: '🔥', shortName: 'fire', wrongNames: ['flame', 'heat', 'burn'] },
  { character: '🌊', shortName: 'waves', wrongNames: ['ocean', 'sea', 'water'] },
  { character: '🌟', shortName: 'star', wrongNames: ['celestial', 'shine', 'sky'] },
  { character: '👍', shortName: 'thumbsup', wrongNames: ['like', 'approve', 'good'] },
  { character: '🤔', shortName: 'thinking', wrongNames: ['ponder', 'consider', 'reflect'] },
  { character: '🎃', shortName: 'pumpkin', wrongNames: ['halloween', 'orange', 'jackolantern'] },
  { character: '🌺', shortName: 'hibiscus', wrongNames: ['flower', 'tropical', 'blossom'] },
  { character: '🍟', shortName: 'fries', wrongNames: ['potato', 'fast food', 'salty'] },
  { character: '🚁', shortName: 'helicopter', wrongNames: ['chopper', 'flight', 'rotorcraft'] },
  { character: '🎭', shortName: 'mask', wrongNames: ['disguise', 'costume', 'theater'] },
  { character: '🎣', shortName: 'fishing', wrongNames: ['angler', 'fisherman', 'catch'] },
  { character: '🚤', shortName: 'speedboat', wrongNames: ['boat', 'fast', 'watercraft'] },
  { character: '🎯', shortName: 'dart', wrongNames: ['target', 'game', 'throw'] },
  { character: '🍇', shortName: 'grapes', wrongNames: ['fruit', 'vine', 'purple'] },
  { character: '🛑', shortName: 'stop', wrongNames: ['sign', 'halt', 'red'] },
  { character: '💡', shortName: 'lightbulb', wrongNames: ['idea', 'innovation', 'illuminate'] },
];