
const emojiArray = [
  { id: 1, character: '😊', shortName: 'smile', wrongNames: ['happy', 'joy', 'laugh'] },
  { id: 2, character: '🌍', shortName: 'earth', wrongNames: ['world', 'globe', 'planet'] },
  { id: 3, character: '🐱', shortName: 'cat', wrongNames: ['kitty', 'feline', 'meow'] },
  { id: 4, character: '🍎', shortName: 'apple', wrongNames: ['fruit', 'red', 'juicy'] },
  { id: 5, character: '🚗', shortName: 'car', wrongNames: ['vehicle', 'automobile', 'drive'] },
  { id: 6, character: '🌈', shortName: 'rainbow', wrongNames: ['color', 'sky', 'weather'] },
  { id: 7, character: '🎉', shortName: 'celebrate', wrongNames: ['party', 'fun', 'happy'] },
  { id: 8, character: '📷', shortName: 'camera', wrongNames: ['photo', 'picture', 'snapshot'] },
  { id: 9, character: '⌚', shortName: 'watch', wrongNames: ['timepiece', 'wristwatch', 'clock'] },
  { id: 10, character: '🎮', shortName: 'gaming', wrongNames: ['game', 'play', 'console'] },
  { id: 11, character: '🍕', shortName: 'pizza', wrongNames: ['slice', 'cheese', 'italian'] },
  { id: 12, character: '🎸', shortName: 'guitar', wrongNames: ['music', 'instrument', 'strings'] },
  { id: 13, character: '📚', shortName: 'book', wrongNames: ['reading', 'literature', 'novel'] },
  { id: 14, character: '🌸', shortName: 'flower', wrongNames: ['blossom', 'petal', 'garden'] },
  { id: 15, character: '🍦', shortName: 'icecream', wrongNames: ['dessert', 'sundae', 'cone'] },
  { id: 16, character: '🎨', shortName: 'art', wrongNames: ['painting', 'creativity', 'canvas'] },
  { id: 17, character: '🚀', shortName: 'rocket', wrongNames: ['space', 'launch', 'spacecraft'] },
  { id: 18, character: '🎤', shortName: 'microphone', wrongNames: ['sing', 'voice', 'recording'] },
  { id: 19, character: '🍔', shortName: 'burger', wrongNames: ['sandwich', 'fast food', 'beef'] },
  { id: 20, character: '🏖️', shortName: 'beach', wrongNames: ['shore', 'coast', 'ocean'] },
  { id: 21, character: '🚲', shortName: 'bike', wrongNames: ['bicycle', 'cycling', 'ride'] },
  { id: 22, character: '🎈', shortName: 'balloon', wrongNames: ['inflate', 'party', 'float'] },
  { id: 23, character: '☕', shortName: 'coffee', wrongNames: ['drink', 'caffeine', 'mug'] },
  { id: 24, character: '🌮', shortName: 'taco', wrongNames: ['mexican', 'food', 'spicy'] },
  { id: 25, character: '🎧', shortName: 'headphones', wrongNames: ['music', 'audio', 'earphones'] },
  { id: 26, character: '🍓', shortName: 'strawberry', wrongNames: ['fruit', 'red', 'juicy'] },
  { id: 27, character: '🏠', shortName: 'house', wrongNames: ['home', 'residence', 'building'] },
  { id: 28, character: '🔥', shortName: 'fire', wrongNames: ['flame', 'heat', 'burn'] },
  { id: 29, character: '🌊', shortName: 'waves', wrongNames: ['ocean', 'sea', 'water'] },
  { id: 30, character: '🌟', shortName: 'star', wrongNames: ['celestial', 'shine', 'sky'] },
];

module.exports = { emojiArray };