# Generated by Django 5.0.1 on 2024-02-05 16:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreview',
            name='review_text',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
