# Generated by Django 5.0.1 on 2024-01-28 21:44

import cards.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_character', models.CharField(max_length=255)),
                ('species', models.CharField(max_length=255)),
                ('house', models.CharField(max_length=255)),
                ('image_url', models.URLField()),
                ('date_of_birth', models.DateField(null=True)),
                ('patronus', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=cards.models.random_price, max_digits=10)),
                ('xp_points', models.IntegerField(default=cards.models.random_xp_points)),
                ('current_owner', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_owner_cards', to=settings.AUTH_USER_MODEL)),
                ('previous_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_owner_cards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
