# Generated by Django 5.0.1 on 2024-01-30 18:41

import cards.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_character', models.CharField(max_length=255)),
                ('species', models.CharField(max_length=255)),
                ('house', models.CharField(max_length=255)),
                ('image_url', models.URLField()),
                ('date_of_birth', models.DateField(null=True)),
                ('patronus', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=cards.models.random_price, max_digits=10)),
                ('xp_points', models.IntegerField(default=cards.models.random_xp_points)),
            ],
        ),
    ]
