# Generated by Django 5.0.1 on 2024-02-09 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='for_sale',
            field=models.BooleanField(default=False),
        ),
    ]
